Public Class StringBank
    Public Shared ReadOnly CatJokes = New String() {
        "What do cats like to eat on a hot day? A mice-cream cone!",
        "Why do cats always get their way? They are very purr-suasive!",
        "How do two cats end a fight? They hiss and make up!",
        "What should you use to comb a cat? A catacomb!",
        "What is a cat's favorite movie? The Sound of Mewsic!",
        "How do you know a cat is agitated? He's having a hissy fit!",
        "What's a cat's favorite magazine? Good Mousekeeping!",
        "Why did the cat wear a fancy dress? She was feline fine!",
        "What's a cat's favorite color? Purr-ple!",
        "Why was the cat afraid of the tree? Because of its bark!",
        "What did the cat say when it was confused? 'I'm purr-plexed!'",
        "What's a cat's favorite dessert? Chocolate mouse!",
        "Where does a cat go when it loses its tail? The re-tail store!",
        "What do you call a cat who lives in an igloo? An eskimew!",
        "How do cats stop crimes? They call claw enforcement!",
        "Why was the cat so agitated? Because he was in a bad mewd!",
        "What do you call a cat who loves to bowl? An alley cat!",
        "What do cats love to do in the morning? Read the mewspaper!",
        "How is cat food sold? Usually, purr the can!",
        "What do baby cats always wear? Diapurrs!",
        "Why are cats great singers? Because they're very mewsical!",
        "Why can't cats play poker in the jungle? Too many cheetahs!",
        "What's another name for a cat's house? A scratch pad!",
        "What should you say to your cat when you leave the house? 'Have a mice day!'",
        "What do cats use to make coffee? A purr-colator!",
        "How does a cat decide what it wants from the store? It flips through the cat-alog!",
        "In what kind of weather is a vet the busiest? When it's raining cats and dogs!",
        "What do you call a cat wearing shoes? A puss in boots!",
        "What type of cat works for the Red Cross? A first aid cat!",
        "Why do cats always win video games? Because they have nine lives!",
        "What state has a lot of cats and dogs? Petsylvania!",
        "What's a cat's favorite game to play with a mouse? Catch!",
        "What do you call a pile of kittens? A meowntain!",
        "What do cats eat for breakfast? Mice Krispies!",
        "Where do cats always fly out of when they travel? Kitty Hawk!",
        "How does a cat sing scales? Do-re-mew!",
        "Why did the cat eat the lemons? He was a sourpuss!",
        "What's a cat's favorite subject in school? Hisss-tory!",
        "What types of cats purr the best? Purrr-sians!",
        "What sports do cats play? Hairball!",
        "Why are cats better than babies? Because you only have to change a litter box once a day.",
        "Who was the most powerful cat in China? Chairman Meow.",
        "What’s a cat’s favorite button on the TV remote? Paws.",
        "Why did the cats ask for a drum set? They wanted to make some mewsic!",
        "What’s a cat’s favorite TV show? Claw and Order.",
        "How did the Mom Cat know she was pregnant? Her test was pawsitive.",
        "What normally happens when kitties go on a first date? They hiss.",
        "What’s a cat’s favorite cereal? Mice crispies.",
        "What color do kittens love the most? Purrple.",
        "What does the cat say after making a joke? 'Just kitten!'",
        "When cats need to go to the airport, who do they call? A tabby.",
        "Why did the cat have to go to an accountant? They got caught up in a purramid scheme.",
        "What made the cat upgrade his phone? He wanted to finally get pawtrait mode.",
        "Why are kittens actually excellent bosses? They have great littership.",
        "What’s it called when all the treats are gone? A cat-astrophe.",
        "Why did the teenage cat call her parents when she found an apartment she liked? She needed them to (cali)co-sign her lease.",
        "What does a choir of cats like to sing? 'Do-Re-Mew.'",
        "Before going after a mouse, what did the dad cat say to his family? 'Let us prey.'",
        "What did the kitten have at their birthday party? A pounce house.",
        "What do you call it when a cat is super-stylish? 'Haute-cat-ture.'",
        "Why did the kitty get an 'A' on their English assignment? They properly used an independent claws.",
        "When a cat doesn’t want to say goodbye, what do they say instead? 'See ya litter!'",
        "Why don’t you want to play Monopoly with a cat? They tend to be cheetahs.",
        "What title does a cat go by in the kitchen? 'The Whisker.'",
        "What was the kitten bowling league called? 'Alley Cats.'",
        "Why is it hard to trust cats? They have many tall tails.",
        "What did the cats do when they realized they had a bad plan? They decided to (cat)nip it in the bud.",
        "Before a cat fight, what is usually said? 'Hold my purrse.'",
        "What do cats quote from the movie Bridesmaids? 'Help me, I’m paw!'",
        "What do cats look for in a significant other? A great purrsonality.",
        "What do you call a cat who became a doctor? 'A first aid kitten.'",
        "What did the mom cat say about her intuition? 'I just had a strong feline.'",
        "Why was the teenage cat sent to his room? He was in a bad meowd.",
        "What did one cat say while her friend was complaining? 'Tail me about it.'",
        "What do cats call a big pile of laundry? A meowtain to climb.",
        "Why did the cat avoid eating lemons? They made him a sour-puss.",
        "What song do kittens always request at dances? 'Mice Mice Baby.'",
        "Why are cats bad at making decisions? They become so purrplexed.",
        "What’s a cat’s favorite sport? Hair ball.",
        "Why do cats hate laptops? They don’t have a mouse.",
        "How did one cat break up with another? She said, 'We’re hisstory!'",
        "Why don’t cats ever say 'YOLO?' They have nine lives.",
        "Which day of the week do cats love the most? Caturday.",
        "Why do cats make horrible DJs? They always paws the tunes.",
        "What did the mom and dad cat say about their wedding day? 'It was unfurrgetable!'",
        "What’s a kitten’s fave way to shop? By cat-alogue.",
        "How did the cat comic know he was funny? The audience was meow-ling with laughter.",
        "Why was the animal lover so untrustworthy? She kept letting the cat out of the bag!",
        "What do cats call a nice dinner? 'A fancy feast.'",
        "What did the sick cat say? 'I feel clawful!'",
        "Why did some cat friends go to the mall? There was a buy-one-get-one-furry deal.",
        "Where do cats enjoy spending a family day? The mew-seum.",
        "What’s a kitten’s favorite kind of sticker? Scratch and sniff."
    }
    Public Shared ReadOnly EatingMessages = New String() {
        "*crunch* *gulp* *lick* YUM!",
        "*loud chewing* Delicious!",
        "*munch* *slurp* BUUUUURP... excuse me!",
        "*gulp* *chew* *crunch* More, please!"
    }
End Class